package campManage.model;

public enum Test {
    SUBJECT_COLLECTION_MATH,
    SUBJECT_COLLECTION_ENGLISH,
    SUBJECT_COLLECTION_SCIENCE,
    SUBJECT_COLLECTION_ART,
    SUBJECT_COLLECTION_EXERCISE
}
